language: python
branches:
  only:
  - master
install:
- pip install pelican
- pip install markdown
- pip install ghp-import
script:
- make github 2> /dev/null
env:
  global:
    secure: RbUBp+5x2u46aln7xzvRGhFzQhf3qBDi+FYO9l8D3bonXVknbpss5TutpheCidGjfxS0Nu61KjjeIFu68U3v9YrMulHhF/6QjGP+INLgKDQAZbpzRU0/nVFhI+df+H4gZKhTRW9RRv9mzhLTMuZy4cJG/YIWyXxR6NHE36xpkGScl5scnS6QrP1Ai6ADZYcaPExJ2ftkq2cmzKM3OPCkfpgt6z2etnA3pHzFLw3QNtdj/Gqp95eKwwr1VHLEqFzkuAPb2oHHbqSkQq5auBYIOetjkplbFHj8AJwNlv6XGOPvrZzGIX50t9XX32b2+qzNCOLbnzEyGsAdVkY8ExNYy14es+/MSgs3Jmn67q+++mOADahgWg5aLCiCW1LoJ5/Lrrm7UpBlMi0GzkZvToKEssWRx4L6C/352nfK55bWD07GdQgtm+Az/0jVPZkZwK5UfX9X76xpYWOPuiKyrqjkmQjtspVbzx1P2AFPFKkwY30RgcxfYQHfCYv9cnwaeFpLcDlIMz48hR1CO0l5UtqxXsEShtdBkpLcBRNSJ0SDvdg1AteyyBJLPmE8vECwC05UQXkNGXtYMDE6yxEeyQuqEQU/HIpbeoLi05PYI5d6tA21d9CAOi9035a9kCGF0wa6a0fRVJRkKhCnzGT3rgsLUOxH+wIsE9vO2Uch1mFcQdw=
