language: python
branches:
  only:
  - master
install:
- pip install pelican
- pip install markdown
- pip install ghp-import
script:
- make github
env:
  global:
  - secure: Cs7yu2rzZ9z2mQ4aE9i3ZFMHauzo3ZSrusFSXUq0dafIAw3nYPwZ9rpJHUFP4kp4/vs4QKDi9fT6VZZM2JSXVmZeRCSgcbKn5MmRzVmraCvG0LwGVovN8wF7K7YUW6nyQo2PAwGK729zH55Vc2gdsSN3M1Lx+Ag5VNldEySYxIKSifjgnvh3qryFp41+ro7LFbOhrwbKPvNAoYQDtg+t4thmmq/C3nKZpRV8L31nbUJcoy48wAQ3ijapaaPEHg/VP8MwC2pUrFQXNwazLcwutlQwf70FQcK0X/AHu2JC+XdD3pDmHYTCOYdYYoAWJGrp0cqfIzdKm2Z4LZHchh/BT82jRnVVePZE++BVRZA1TFJnSfzgquus7aolMmOXEKthSpAObQ4iKE06+VSZChi6RvgLzKCnxkIdDqlQvaAdgfkXbteHHhECSARCwRda0rHTCERWwmEL52F/kdEbrQmUTu7m4wGmwCw7XrK4xIYo6r1SZLQY8W+GCKULrfBOsdBFa2/ZrgaieXWg8MdHrE6VW6Y9oHz57dCnekzn7hSN7yY3SAdoLhfLOGqO/KUgk/ffp/pwq7kppNMkvK/YV6TyCAN8esN97u04mqNfWSl7lfBWpPxgxg2XTJ0Ac0hLgF2eC6KgFYVh1vyp2SnnOwVcd3/0Jo1wizhzbj8Xw8NkYLo=
  - secure: EEm6GLP7Flyx0Q2zUOBw8uhcDGF8fbgCzMCYUHBiUsXKrttXIN7d1IIILdgZ34Bvjbj97k19zWfDnmKj8zGooK68dBGLnVrwi1ZVB4x5rgQXOyyN2qFuGdMo+T4sMMnMKNJ82WDoOw2mdePyDYXsavhmKRLAjdU/pEl0d7IhD8fSjLZoj24q1s8+/w/X9mXhmRv1Z4903JaLLWdP1d3lwoAC8zQvLMzvJMQJ7IFH0798cvDcV4CdhY13wblYpDsJ0q2W3e4u3fi9ijy3QbI0qas5SKCAyM1EIxsv7mKM6csI+3NRm9YM4ZKy4qbex4yPvDA+IY5AcQW6Zuabu0jKQSVIigWdp8kI2XqRosX0wa0U41GhRlcQC6Luzkinlf3ytMlnkkmz7xRuVeylKOTGq1zXQnRwMjoisNMFlpdxqwcD3Kwjs8TeczQLdm807LagjrRUIHGl/hdXy2QdF2j2ol8jLtZM7jfP6pf7v00qLdTpUGb4pOGjw0gVYdXa2TGXDWp3lx4YQ4XdPxKGHqF85YNwmHyjfLSA0N7xIGQjryVidXrruK6jYuLzzpgr/fa9wGI1o0Y1NHwP9k/oZIdNXRPmI6kL4RhbV20aPzAjfOkfXS94sRBeppbRv5RtAIY4rNQkyZ5954FykpqcAnOow7/7ji0b/OGE5W0lS1pe5eY=
