language: python
branches:
  only:
  - master
install:
- pip install pelican
- pip install markdown
- pip install ghp-import
script:
- make github 2> /dev/null
env:
  global:
  - secure: K3WfSGH5NLJBmMAEDaPLUBDj2pwHJaeSwWGwC4eECmUii+gY+y8gh8zzV9EQbxKMuXjkQdrhDRwSPE59N3F+WBWitkj6GrdPdqfo0xz2xMuW8iHR1Di4UxsHEvPcHpq8fEZZR4u2eYG4KcCCejKvI3vUvj+URCoWcs/D1Dqr7Uus4SAcFQHJKu/31eYX9bczYkDizJLNzKgS4v2/qtqEnh1JLtHjT8StbQ5I9fFSQ3a3lPBZ1orcRyfQpCGUGmqM0KjjvGZn6Gf4U6l/OjVjkMF4VCwLdtDlU6FfX6FWk48PS+QjkBkYZKpobovoibmThi2EBsaPRRJQV/tM9kboFBcpzlpi+hE4MiguLLU9n27Jy75WiM9CAC1x28Y/qSs9G100lKv4CIQ0dJ7oDOc88JTSPFkNz7KBTiS93hdPzOKPGRPqflP4jODfoXBnN48lYT4Mzwvaq5Lsix2MaV1NLxHj1yZx7hGj3lPmjFPHaT6zuP1FhySgxZwGV2qdueRDtH/3ywe2cOZQMUI5zMPXt/Nn/tPJix+q5hBALnujy+Gnv6UAcy/sUCXtChpIlLciEtuneEWzaxcyZqYzO68p0BnMZjqQP1BjA2vMZoBhNGd2MnJy1L3nNMI/h8p3mMjNn5Ip8nIDfRSaVUQlE3+w7hQ0AcUQ9h2xswQ4v2VpBj4=
